### ISSUE TITLE
Misalignment of image if padding is not zero

### ISSUE THREAD

**Issue by kumattau** [microo8/alacritty-sixel#5]
Image is misaligned if padding is not zero.

.alacritty.yml
```yaml
window:
  padding:
    x: 20
    y: 20
```

![image](https://user-images.githubusercontent.com/171798/164917024-68953ec1-47b0-4d46-a007-469e750f13f0.png)
